{{- if .Values.container.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stasico.fullname" . }}-env-secrets
  labels:
    app.kubernetes.io/name: {{ include "stasico.name" . }}
    helm.sh/chart: {{ include "stasico.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $val := .Values.container.secretEnv }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end }}
{{- end }}
