{{- $Outer := . }}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stasico.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stasico.name" . }}
    helm.sh/chart: {{ include "stasico.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
{{- range $portName, $portInfo := (required "Please define .Values.service.ports[] when using a Service!" .Values.service.ports) }}
    - name: {{ $portName }}
{{ toYaml $portInfo | indent 6 }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "stasico.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
